### ISSUE TITLE
how to remove percent of progress?

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [layounisl/CircleProgressBar#1]
how to remove percent of progress?

**Comment by sunkuu7** [comment]
Hello, you could simply fork and remove the percentage sign on the lines [16](https://github.com/layounisl/CircleProgressBar/blob/cf2047291c68083e9e1d6bfdc08b0c0ce6bbb0d7/Animation/CircleProgressBar.swift#L16) and [93](https://github.com/layounisl/CircleProgressBar/blob/cf2047291c68083e9e1d6bfdc08b0c0ce6bbb0d7/Animation/CircleProgressBar.swift#L93) , if i have free time i will try to work more on this pod to make it more customizable. Cheers !
